# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4fc4969506f04c0de6ad994bcc1af8c3a74f6586d0378c1f4b654351f55e877c149de9c626a83a75fd4dd600286e7a497eee506d50cc8bd5bd0214437bfbdac

test:
  secret_key_base: 91e654be198d9646b3b5429c12bd2cf348ecbb09612b2140725957174d0c861be7bf72717a0da38fdaa6ddf9063330173acb6bc611e4baf812dfdef2c027beba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
